### ISSUE TITLE
Installation Problem and fix?

### ISSUE THREAD

**Issue by RamseyN** [vertesy/MarkdownReports#103]
The instructions for installation say to input the following:

# install.packages("devtools"); # If you don't have it.
require("devtools")
devtools::install_github(repo = "vertesy/MarkdownReports/MarkdownReports")

This came back with the error

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`vertesy`) and repo name (`MarkdownReports`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

It was only until I took out the second repeat of Markdown reports that the installation worked

> devtools::install_github(repo = "vertesy/MarkdownReports")

Is this a bug? Or is there something I'm missing

**Comment by vertesy** [comment]
Sorry, it was mistake in the readme. Correct path:

```r
# install.packages("devtools"); # If you don't have it.
require("devtools")
devtools::install_github(repo = "vertesy/MarkdownReports")
```

Please note that the current version has a major error: #104

**Comment by vertesy** [comment]
@RamseyN Could you please try to install it, and paste the error message (if you get one)? Thank you !
